### ISSUE TITLE
不应该继续使用糟糕的 OpenVPN TUN 驱动。

### ISSUE THREAD

**Issue by h0gan1ee** [NetchX/NetchBinaries#1]
众所周知，OpenVPN 的 TUN 驱动 CPU 占用很高，效率很低，非常不好用。
但是 HTTP 代理无法代理 DNS 解析以及其他协议，也带来了一些问题。

因此，在此恳求开发者更换到这个更好的 TUN 驱动吧，谢谢了：
https://www.phoronix.com/scan.php?page=news_item&px=WinTUN-Windows-TUN-Driver

**Comment by fanck0605** [comment]
![image](https://user-images.githubusercontent.com/28819315/78473364-a23b6500-7772-11ea-8e57-d8b55653b603.png)
这个糟糕的驱动还有内存泄漏问题。。
